# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/simpleapp-nbdev',
                'doc_host': 'https://rajendrakumaryadav.github.io',
                'git_url': 'https://github.com/rajendrakumaryadav/simpleapp-nbdev',
                'lib_path': 'simpleapp'},
  'syms': { 'simpleapp.app': { 'simpleapp.app.main': ('app.html#main', 'simpleapp/app.py'),
                               'simpleapp.app.print_sys_info': ('app.html#print_sys_info', 'simpleapp/app.py')},
            'simpleapp.core': {'simpleapp.core.foo': ('core.html#foo', 'simpleapp/core.py')}}}
