# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/001_app.ipynb.

# %% auto 0
__all__ = ['logger', 'print_sys_info', 'main']

# %% ../nbs/001_app.ipynb 2
import sys
from fastcore.script import *
import logging

# %% ../nbs/001_app.ipynb 3
logger = logging.getLogger(__name__)
# format
logging.basicConfig(format='%(asctime)s %(levelname)s - %(message)s', datefmt='%m/%d/%Y %I:%M:%S %p')
# set level
logger.setLevel(logging.DEBUG)
def print_sys_info():
    logger.info("Python Version: %s", sys.version)
    logger.info("Python Executable: %s", sys.executable)
    logger.info("Python Platform: %s", sys.platform)
    logger.info("Python Prefix: %s", sys.prefix)
    logger.info("Python Executable: %s", sys.executable)

# %% ../nbs/001_app.ipynb 5
@call_parse
def main():
    print_sys_info()
